version: '3.8'
services:
  backend:
    build: .
    container_name: pb-backend
    environment:
      MONGO_URI: "mongodb://mongo:27017/fastapi_app"
      JWT_SECRET: "change_me_to_a_strong_secret"
      JWT_ALGORITHM: "HS256"
      JWT_EXP_MINUTES: 60
      APP_HOST: "0.0.0.0"
      APP_PORT: 8000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"
      ZITADEL_OPERATOR_ISSUER: "https://pica-bo-k7arya.us1.zitadel.cloud"
      ZITADEL_OPERATOR_AUDIENCE: "operator-api"
      ZITADEL_OPERATOR_JWKS_URL: "https://pica-bo-k7arya.us1.zitadel.cloud/oauth/v2/keys"
      ZITADEL_EXPLORER_ISSUER: "https://pica-bo-k7arya.us1.zitadel.cloud"
      ZITADEL_EXPLORER_AUDIENCE: "explorer-api"
      ZITADEL_EXPLORER_JWKS_URL: "https://pica-bo-k7arya.us1.zitadel.cloud/oauth/v2/keys"
      INTERNAL_SERVICE_ISSUER: "https://pica-bo-k7arya.us1.zitadel.cloud/oauth/v2/keys"
      INTERNAL_SERVICE_AUDIENCE: "internal-api"
      INTERNAL_SERVICE_JWKS_URL: "https://pica-bo-k7arya.us1.zitadel.cloud/.well-known/jwks.json"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
  mongo:
    image: mongo:6.0
    container_name: pb-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: pb-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongo_data:
  redis_data:

  